server:
  port: 9010

spring:
  application:
    name: ecommerce-user-service
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
  sleuth:
    sampler:
      #采样100%
      probability: 1.0