server:
  port: 9000

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://47.111.162.136:9411
    sender:
      type: web
  sleuth:
    sampler:
      #采样100%
      probability: 1.0